/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_stdnull_runmap_common_AppConfig */

#ifndef _Included_com_stdnull_runmap_common_AppConfig
#define _Included_com_stdnull_runmap_common_AppConfig
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_stdnull_runmap_common_AppConfig
 * Method:    getWeixinAppId
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_stdnull_runmap_common_AppConfig_getWeixinAppId
  (JNIEnv *, jclass);

/*
 * Class:     com_stdnull_runmap_common_AppConfig
 * Method:    getDbBackupBaseUrl
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_stdnull_runmap_common_AppConfig_getDbBackupBaseUrl
  (JNIEnv *, jclass);

/*
 * Class:     com_stdnull_runmap_common_AppConfig
 * Method:    runCheck
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_stdnull_runmap_common_AppConfig_runCheck
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
